### ISSUE TITLE
The icons are not displayed correctly. Instead of the icons, a square is displayed as a placeholder.

### ISSUE THREAD

**Issue by garderobier** [yoyurec/logseq-tabler-picker#1]
**Info:**
- OS: macOS Venture 13.2.1
- Logseq ver: 0.8.18
- Plugin ver: 1.4.0
- Theme name: miA theme 1.4.9

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
The icons are not displayed correctly. Instead of the icons, a square is displayed as a placeholder.

**To Reproduce:**
- Use /Tabler icon picker to select an icon.
- press ENTER
- Icon will be displayed as square placeholder

**Expected behavior:**
Icons are displayed correctly.

**Screenshots**
<img width="551" alt="Screenshot 2023-03-08 at 15 34 01" src="https://user-images.githubusercontent.com/101436860/223741417-4e7a0bb9-c9f5-4492-84f9-74e45382a787.png">

**Comment by yoyurec** [comment]
have you tried to disable all other plugins + restart Logseq?
something is overriding font CSS
i've installed Mia theme and everything is ok

**Comment by garderobier** [comment]
Yes I did, but nothing changed. All plugins disabled and empty custom.css

**Comment by yoyurec** [comment]
very strange... can you inspect them via devTools?
* open devtools `Command+Option+i`
* Elements tab
* inspect element
* computed styles tab
* `font-family` property value and source

https://user-images.githubusercontent.com/137919/223872528-852e7201-9b8c-4eec-85ef-e3d16a307e99.mp4

do as on video and post screen plz, like this one
![image](https://user-images.githubusercontent.com/137919/223872429-1a3f66e8-4647-43b5-beff-0e80cd499e69.png)

**Comment by garderobier** [comment]
I didn't see the tablerPicker.css
Here the screenshots. I hope that helps.

<img width="1640" alt="grafik" src="https://user-images.githubusercontent.com/101436860/224369290-f2ad6885-40a6-4c81-b52d-92443734e27a.png">

<img width="628" alt="grafik" src="https://user-images.githubusercontent.com/101436860/224369028-a1b1a017-71ca-4349-b678-a0cdca6ee4d4.png">

**Comment by yoyurec** [comment]
edit you also do screen, when text is not in "edit mode"

**Comment by yoyurec** [comment]
yes, it helps. Mia theme creator using the wrong approach... need to create an issue in his repo. will do

**Comment by yoyurec** [comment]
https://github.com/playerofgames/logseq-mia-theme/issues/15
